[build-system]
requires = ['setuptools>=61', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'localgraph'
version = '0.1.5'
description = 'Local graph estimation with pathwise feature selection'
readme = 'README.md'
requires-python = '>=3.6'
authors = [
    { name = 'Omar Melikechi', email = 'omar.melikechi@gmail.com' }
]

dependencies = [
    'ipss>=1.1.1',
    'matplotlib>=3.0.0',
    'networkx>=2.0',
    'numpy>=1.16.0'
]

classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent'
]

[tool.setuptools.packages.find]
include = ['localgraph', 'localgraph.*']

[tool.setuptools]
include-package-data = true